import { createApp } from "vue";
import App from "./App.vue";
import "bootstrap/dist/css/bootstrap.min.css";
// import { library } from "@fortawesome/fontawesome-svg-core";
// import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
// import { faUserSecret } from "@fortawesome/free-solid-svg-icons";
// library.add(faUserSecret);
import router from "./routes";
import store from "./store/Index";
const app = createApp(App).use(router).use(store);
// component("font-awesome-icon", FontAwesomeIcon);
app.mount("#app");
